credentials:
  sashi:
    api_key: f9dtnoqozzcg5a51
    secret_key: dz6a70kj5gdvo84k16gexspsgwyo159e
    username : OL5402
    password : Arepalli123$
    authenticator_token : 7YIPADTOYPGO3R2LFL3ZKNSPNVJWNEH7
  madhu:
    api_key: erenpd2psfhkugz4
    secret_key: flhvf7rd4pa3jqhq9g5gsbbj4rny83fi
    username: HOZ563
    password: Skanth123$
    authenticator_token: GZZ3XZFJQBEUSY63RXH4SLCPZQZB5XEB
